version: '3'
services:
  schema-creator:
    build: .
    ports:
      - ${EXTERNAL_PORT-5005}:80
    restart: always
    environment:
      TMP_BASE_PATH: './tmp'
      DEFAULT_PROGRAM_NAME: "ProgramName"